fast_furious/urls.py
from fast_furious.views import *
from django.urls import path
app_name='fast_furious'
urlpatterns=[
    path('cars1/',cars1,name='cars1')
]

furious_world/urls.py
from django.contrib import admin
from django.urls import path,include
import fast_furious,toofast_toofurious
from tokyo_drift.views import *
urlpatterns = [
    path('admin/', admin.site.urls),
    path('fast_furious/',include('fast_furious.urls')),
    path('toofast_toofurious/',include('toofast_toofurious.urls')),
    path('cars3/',cars3,name='cars3'),
]

toofast_toofurious/urls.py
from toofast_toofurious.views import *
from django.urls import path
app_name='toofast_toofurious'
urlpatterns=[
    path('cars2/',cars2,name='cars2')
]

fast_furious/models.py
from django.db import models

# Create your models here.

tokyo_drift/models.py
from django.db import models

# Create your models here.

toofast_toofurious/models.py
from django.db import models

# Create your models here.

fast_furious/views.py
from django.shortcuts import render

# Create your views here.
def cars1(request):
    return render(request,'cars1.html')

tokyo_drift/views.py
from django.shortcuts import render

# Create your views here.
def cars3(request):
    return render(request,'cars3.html')

toofast_toofurious/views.py
from django.shortcuts import render

# Create your views here.
def cars2(request):
    return render(request,'cars2.html')

templates/cars1.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body style="background-color:gray;">
    <center>
        <h1 style="color: blueviolet;"><marquee>Fast_Furious</marquee></h1>
        <h1 style="color: brown;">Fast & Furious is the first movie of the series</h1>
        <a href="{% url 'toofast_toofurious:cars2' %}">Take to 2nd movie</a><br>
        <a href="{% url 'cars3' %}">Take to 3rd movie</a>
    </center>
</body>
</html>

templates/cars2.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body style="background-color: azure;">
    <center>
        <h1 style="color: crimson;">toofast_toofurious</h1>
        <h1 style="color: darkred;">This is the second movie in the series</h1>
        <h1>There are many new elements are there in this movie</h1>
        <a href="{% url 'fast_furious:cars1' %}">Take to 1st movie</a><br>
        <a href="{% url 'cars3' %}">Take to 3rd movie</a>
    </center>
</body>
</html>

templates/cars3.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body style="background-color: beige;">
    <center>
        <h1 style="color: firebrick;">Tokyo_Drift</h1>
        <h1 style="color: tomato;">This is the third movie in the series</h1>
        <h1 style="color: tomato;">In this the whole story is different the only thing in common is cars & raccing there are many twists and more action is available</h1>
        <a href="{% url 'fast_furious:cars1' %}">Take to 1st movie</a><br>
        <a href="{% url 'toofast_toofurious:cars2' %}">Take to 2nd movie</a>
    </center>
</body>
</html>